#ifndef APP_CONFIG_H
#define APP_CONFIG_H

/*
 * SEN65 — Read Measured Values, Command 0x0446 (RX 24 bytes com CRC / 2 bytes):
 * - PM1/2.5/4/10 (uint16): ug/m3 = valor / 10. Desconhecido: 0xFFFF.
 * - Ambient Humidity (int16): %RH = valor / 100. Desconhecido: 0x7FFF.
 * - Ambient Temperature (int16): Celsius = valor / 200. Desconhecido: 0x7FFF.
 * - VOC Index (int16): indice = valor / 10. Desconhecido: 0x7FFF.
 * - NOx Index (int16): indice = valor / 10. Desconhecido: 0x7FFF.
 *
 * O driver guarda em sen65_data_t: PM em bruto (0,1 ug/m3); RH/T em ticks I2C;
 * VOC/NOx ja como indice (valor I2C / 10), exceto 0x7FFF mantido como invalido.
 */

#define SENSOR_QUEUE_SIZE 10
#define SENSOR_READ_INTERVAL_MS 1000
#define SENSOR_WARMUP_TIME_MS 5000
#define SENSOR_TASK_STACK 4096
#define SENSOR_TASK_PRIORITY 5
#define PROCESS_TASK_STACK 4096
#define PROCESS_TASK_PRIORITY 4

#define EMA_FAST_ALPHA 20
#define EMA_FAST_DIV 100

#define BASELINE_ALPHA 5
#define BASELINE_DIV 100
#define PM_NOISE_FLOOR 2
#define VOC_NOISE_FLOOR 1
#define NOX_NOISE_FLOOR 1

#define EVENT_PM_START_THRESHOLD 40
#define EVENT_VOC_START_THRESHOLD 10
#define EVENT_PM_ACTIVE_THRESHOLD 80
#define EVENT_VOC_ACTIVE_THRESHOLD 8
#define EVENT_PM_END_THRESHOLD 15
#define EVENT_VOC_END_THRESHOLD 2
#define EVENT_PM_IDLE_THRESHOLD 5
#define EVENT_VOC_IDLE_THRESHOLD 1

#define ADAPTIVE_IDLE_RING 120
#define ADAPTIVE_MIN_SAMPLES 24
#define ADAPT_K_PM 4.0f
#define ADAPT_K_VOC 4.0f
#define ADAPT_PM_START_FLOOR 22
#define ADAPT_VOC_START_FLOOR 5
#define ADAPT_PM_ACTIVE_SCALE_NUM 2
#define ADAPT_PM_ACTIVE_SCALE_DEN 1
#define ADAPT_VOC_ACTIVE_SCALE_NUM 4
#define ADAPT_VOC_ACTIVE_SCALE_DEN 5
#define ADAPT_PM_END_SCALE_NUM 3
#define ADAPT_PM_END_SCALE_DEN 8
#define ADAPT_VOC_END_SCALE_NUM 1
#define ADAPT_VOC_END_SCALE_DEN 5
#define ADAPT_PM_IDLE_SCALE_NUM 1
#define ADAPT_PM_IDLE_SCALE_DEN 8
#define ADAPT_VOC_IDLE_SCALE_NUM 1
#define ADAPT_VOC_IDLE_SCALE_DEN 10

#define ADAPT_VAPE_SOFT_K 3.2f
#define ADAPT_VAPE_SOFT_BIAS 8
#define ADAPT_VAPE_MED_K 5.5f
#define ADAPT_VAPE_MED_BIAS 18
#define ADAPT_VAPE_HIGH_K 9.0f
#define ADAPT_VAPE_HIGH_BIAS 35

#define DETECTION_SCORE_THRESHOLD 68

#define VAPE_VOC_SPIKE_SOFT 40
#define VAPE_VOC_SPIKE_MED 80
#define VAPE_VOC_SPIKE_HIGH 150
#define VAPE_NOX_SPIKE_MAX 1
#define VAPE_PM_SPIKE_SOFT_CAP 220
#define VAPE_PM_VOC_RATIO_LOW 0.65f
#define VAPE_PM_VOC_RATIO_HIGH 1.80f

#define CIG_PM_SPIKE_SOFT 95
#define CIG_PM_SPIKE_MED 140
#define CIG_VOC_SPIKE_SOFT 7
#define CIG_NOX_SPIKE_SOFT 1
#define CIG_NOX_SPIKE_STRONG 2
#define CIG_PM_VOC_RATIO_MIN 0.22f

#define CIG_SIGNATURE_RATIO_MIN 0.18f
#define CIG_NOXLESS_PM_SPIKE 110
#define CIG_NOXLESS_VOC_SPIKE 8
#define CIG_NOXLESS_RATIO_MIN 0.26f
#define CIG_NOXLESS_CO2_SPIKE 10
#define CIG_NOXLESS_SCORE_BONUS 24
#define CIG_DISAMBIG_FIRE_SUB 26
#define CIG_FIRE_CAP_ONLY_ABOVE 88
#define CIG_ALERT_OVER_FIRE 6

#define PERFUME_VOC_THRESHOLD 12
#define PERFUME_PM_MAX 20
#define DUST_PM_THRESHOLD 150
#define DUST_VOC_MAX 2

#define DECAY_DROP_MIN_MAG 3
#define DECAY_VAPE_SHAPE_BONUS 18
#define DECAY_DUST_PM10_VS_PM1_NUM 14
#define DECAY_DUST_PM10_VS_PM1_DEN 10
#define DECAY_DUST_SHAPE_BONUS 22

#define CROWD_CO2_EMA_ALPHA 20
#define CROWD_CO2_EMA_DIV 100
#define CROWD_CO2_DERIV_PPM_PER_MIN 200
#define CROWD_CO2_MIN_PPM 520
#define CROWD_CO2_STREAK_SAMPLES 4

#define FIRE_SCORE_THRESHOLD 72
#define FIRE_PM_SPIKE_HIGH 380
#define FIRE_PM_SPIKE_MED 240
#define FIRE_PM_SPIKE_DUST_VOC_MAX 4
#define FIRE_VOC_SPIKE_HIGH 18
#define FIRE_VOC_SPIKE_MED 11
#define FIRE_PM_VOC_COMBO_PM 190
#define FIRE_PM_VOC_COMBO_VOC 10
#define FIRE_SUSTAIN_DURATION 10
#define FIRE_SUSTAIN_PM_SPIKE 165
#define FIRE_SUSTAIN_VOC_SPIKE 8
#define FIRE_PEAK_PM25_MIN 280
#define FIRE_TEMP_DELTA_TICKS 90

#define FIRE_PYROLYSIS_VOC_MIN 14
#define FIRE_PYROLYSIS_PM_MAX 95
#define FIRE_PYROLYSIS_NOX_MIN 1
#define FIRE_PYROLYSIS_CO2_SPIKE_MIN 6
#define FIRE_PYROLYSIS_VOC_BONUS 22
#define FIRE_PYROLYSIS_NOX_BONUS 10
#define FIRE_PYROLYSIS_CO2_BONUS 8
#define FIRE_PYROLYSIS_HANDOFF_PM_MIN 55
#define FIRE_PYROLYSIS_HANDOFF_VOC_MIN 10
#define FIRE_PYROLYSIS_HANDOFF_BONUS 14

#define PURE_AIR_CO2_MIN_PPM 395
#define PURE_AIR_CO2_MAX_PPM 430
#define PURE_AIR_STREAK_SAMPLES 300
#define PURE_AIR_PM_SPIKE_MAX 2
#define PURE_AIR_VOC_SPIKE_MAX 2
#define PURE_AIR_NOX_SPIKE_MAX 1
#define PURE_AIR_SAVE_MIN_INTERVAL_US (24LL * 3600 * 1000000)

#define SERIES_RECORD_ENABLE 1
#define SERIES_RECORD_RING_CAPACITY 240
#define SERIES_STREAM_CSV_LINE 0
#define SERIES_AUTO_DUMP_INTERVAL_SAMPLES 0
#define SERIES_AUTO_DUMP_CHUNK_LINES 24

#define SERIES_BLACKBOX_PRE_SEC 60
#define SERIES_BLACKBOX_POST_SEC 30

/* Nivel legado 4 faixas (CO2 edificio); AQI EPA e a referencia principal no MQTT. */
#define AIR_UI_PM25_GOOD_MAX 15
#define AIR_UI_PM25_SLIGHT_MAX 35
#define AIR_UI_PM25_MODERATE_MAX 55

#define AIR_UI_PM10_GOOD_MAX 45
#define AIR_UI_PM10_SLIGHT_MAX 100
#define AIR_UI_PM10_MODERATE_MAX 150

#define AIR_UI_CO2_GOOD_MAX 800
#define AIR_UI_CO2_SLIGHT_MAX 1000
#define AIR_UI_CO2_MODERATE_MAX 1500

#define MQTT_AIR_ENABLE 1
#define MQTT_BROKER_URI "mqtt://192.168.51.87:1883"
#define MQTT_TOPIC_AIR "indoor/air/reading"
#define MQTT_QOS_AIR 1
#define MQTT_RETAIN_AIR 0

#define BLE_PROV_POP "abcd1234"
#define BLE_PROV_CLEAR_STORED_WIFI 0

#define BLE_PROV_RESET_GPIO (-1)
#define BLE_PROV_RESET_GPIO_ACTIVE_LOW 1
#define BLE_PROV_RESET_HOLD_MS 5000
#define BLE_PROV_RESET_WINDOW_MS 20000

#endif
